# Generated by Django 3.0.3 on 2020-02-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instrument_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='youtube_url',
            field=models.CharField(default='https://www.youtube.com/watch?v=7IR7xB3VPPc', max_length=100),
        ),
    ]
