# Generated by Django 3.0.3 on 2020-02-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200215_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
